spring:
  application:
    name: Content-Checker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content-checker?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  elasticsearch:
    uris: "https://localhost:9200"
    socket-timeout: "10s"
    username: "elastic"
#    password: "gwO+DhAFKGhJmIcI3798"
    password: "b=zI1++1St_T63DbE0dG"
  thymeleaf:
    cache: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #password: xxx
      database: 1



mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.eva.check.pojo
  globalConfig:
    dbConfig:
      idType: AUTO

server:
  shutdown: "graceful"
  servlet:
    register-default-servlet: true

content-check:
  mq: eventBus
  process-log: true
#  mq: rocketMq
#  mq: eventBus



#
#  mvc:
#    static-path-pattern: "/resources/**"

# rabbitmq 特殊配置
rocketmq:
  # 阿里云测试环境
  name-server: http://localhost:9876
#  name-server: http://10.0.0.96:9876
  #  name-server: localhost:9876
  producer:
    group: sfis-content-checker-producer-group
    #customizedTraceTopic: SFIS_TRACE_TOPIC
